### ISSUE TITLE
Fix todo tags

### ISSUE THREAD

**Issue by ll-nick** [KIT-MRT/arbitration_graphs#23]
Here's a list of all todo tags in the current code base. Let's fix them.

- [ ] https://github.com/KIT-MRT/arbitration_graphs/blob/7f2046a8ffe66ddcacb37b86b688853c40411a83/include/arbitration_graphs/arbitrator.hpp#L44
- [ ] https://github.com/KIT-MRT/arbitration_graphs/blob/7f2046a8ffe66ddcacb37b86b688853c40411a83/include/arbitration_graphs/arbitrator.hpp#L45
- [ ] https://github.com/KIT-MRT/arbitration_graphs/blob/7f2046a8ffe66ddcacb37b86b688853c40411a83/include/arbitration_graphs/arbitrator.hpp#L61
- [ ] https://github.com/KIT-MRT/arbitration_graphs/blob/7f2046a8ffe66ddcacb37b86b688853c40411a83/test/cost_arbitrator.cpp#L93
- [ ] https://github.com/KIT-MRT/arbitration_graphs/blob/7f2046a8ffe66ddcacb37b86b688853c40411a83/test/cost_arbitrator.cpp#L97
- [ ] https://github.com/KIT-MRT/arbitration_graphs/blob/7f2046a8ffe66ddcacb37b86b688853c40411a83/test/cost_arbitrator.cpp#L105
- [ ] https://github.com/KIT-MRT/arbitration_graphs/blob/7f2046a8ffe66ddcacb37b86b688853c40411a83/test/cost_arbitrator.cpp#L108
